'use strict';
const $=id=>document.getElementById(id), M=ACO;
let edges=M.defaults(), iteration=0, best=null, history=[], records=[], running=false, pending=null, progress=0, previous=null, selected='B2', lastFrame=0;
const f=(n,d=1)=>Number.isFinite(n)?n.toFixed(d):'통행 불가';
const name=id=>M.nodes.find(n=>n.id===id).name;
const path=p=>p?.nodes?.map(name).join(' → ')||'아직 발견하지 못함';
const routeName=p=>p?.ids?.length?`경로 ${p.ids[0][0]}`:'경로 없음';
const config=()=>Object.fromEntries(['count','limit','alpha','beta','rho'].map(id=>[id,Number($(id).value)]));
function normalize(el){let v=Number(el.value);if(!Number.isFinite(v)||el.value==='')v=Number(el.min);v=Math.max(Number(el.min),Math.min(Number(el.max),v));if(['count','limit'].includes(el.id))v=Math.round(v);el.value=v;return v;}
function setStatus(){ $('play').textContent=running?'Ⅱ 일시정지':'▶ 탐색 재생';$('status').textContent=`${iteration} / ${config().limit} 반복 · ${running?'탐색 중':pending?'일시정지':iteration>=config().limit?'탐색 완료':'대기'}`;}
function clearSearch(){running=false;pending=null;progress=0;iteration=0;best=null;history=[];records=[];edges.forEach(e=>e.tau=1);render();}
function snapshot(){const p=best||M.dijkstra(edges);return p?{...p,ids:[...p.ids],nodes:[...p.nodes],source:best?'ACO 추천':'다익스트라 기준 (ACO 탐색 전)'}:{source:'도달 가능한 경로 없음',ids:[],nodes:[],time:Infinity};}
function roadChange(change){previous=snapshot();change();clearSearch();fillEditor();}
function begin(){if(iteration>=config().limit)return;pending=M.iteration(edges,config());progress=0;}
function commit(){if(!pending)return;iteration++;pending.forEach((a,i)=>{records.push({...a,round:iteration,number:i+1});if(!a.failed&&(!best||a.time<best.time))best=a;});records=records.slice(-500);history.push(best?.time??null);pending=null;progress=0;if(iteration>=config().limit)running=false;render();}
function drawMap(t=0){const max=Math.max(1,...edges.map(e=>e.tau));let s='<defs><pattern id="grid" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M 40 0 H 0 V 40" fill="none" stroke="#e8edef"/></pattern></defs><rect width="800" height="510" fill="url(#grid)"/>';
 s+='<path d="M0 476 Q200 452 380 483 T800 478" fill="none" stroke="#daebf1" stroke-width="26"/><text x="620" y="494" fill="#89a9b7" font-size="11">가상의 도심 하천</text>';
 [[325,160,90,43],[350,329,95,44],[98,340,48,60],[587,153,60,40]].forEach(([x,y,w,h],i)=>s+=`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="9" fill="${i===2?'#dfeddd':'#e4eaed'}"/>`);
 for(const e of edges){const a=M.nodes.find(n=>n.id===e.from),b=M.nodes.find(n=>n.id===e.to),color=e.closed?'#a6acb0':e.congestion>=2?'#d76455':e.congestion>1?'#dc983b':'#389e8d',w=4+10*e.tau/max;
 const recommended=best?.ids.includes(e.id);s+=`<g data-edge="${e.id}" tabindex="0" role="button" aria-label="${e.id} 도로 편집"><title>${e.id}: ${f(M.time(e))}분, 페로몬 ${f(e.tau,2)}</title><line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="${selected===e.id?'#a3dcd9':recommended?'#bfd9e7':'#dfe6e9'}" stroke-width="${w+9}"/><line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="${color}" stroke-width="${w}" ${e.closed?'stroke-dasharray="8 7"':''}/><line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="transparent" stroke-width="30"/><rect x="${(a.x+b.x)/2-44}" y="${(a.y+b.y)/2-28}" width="88" height="22" rx="5" fill="white" opacity=".95"/><text x="${(a.x+b.x)/2}" y="${(a.y+b.y)/2-13}" text-anchor="middle" font-size="11" fill="#41545e">${e.id} · ${e.closed?'통제':f(M.time(e))+'분'}</text></g>`;}
 for(const n of M.nodes){const terminal=['H','D'].includes(n.id);s+=`<circle cx="${n.x}" cy="${n.y}" r="${terminal?24:10}" fill="${terminal?(n.id==='H'?'#087e83':'#dd735b'):'white'}" stroke="${terminal?'white':'#6d8590'}" stroke-width="3"/>${terminal?`<text x="${n.x}" y="${n.y+7}" fill="white" font-size="22" text-anchor="middle">${n.id==='H'?'+':'!'}</text>`:''}<text x="${n.x}" y="${n.y+(terminal?43:29)}" text-anchor="middle" font-size="13" font-weight="600" fill="#28434e">${n.name}</text>`;}
 if(pending){pending.forEach((a,i)=>{const local=Math.max(0,Math.min(.999,(t-i/pending.length*.23)/.77));const segment=local*Math.max(a.ids.length,1),k=Math.min(Math.floor(segment),a.nodes.length-1),u=M.nodes.find(n=>n.id===a.nodes[k]),v=M.nodes.find(n=>n.id===a.nodes[Math.min(k+1,a.nodes.length-1)]),q=segment-Math.floor(segment);const x=u.x+(v.x-u.x)*q,y=u.y+(v.y-u.y)*q;s+=`<circle cx="${x}" cy="${y+(i%5-2)*3}" r="4" fill="#ffe08a" stroke="#69502a" stroke-width="1.3"/>`;});}
 $('map').innerHTML=s;
}
function showProb(a){const decisions=a?.decisions||[{node:'H',choices:M.choices('H',['H'],edges,config().alpha,config().beta)}];$('probabilities').innerHTML=`<p>${a?'선택한 개미의 실제 추첨 당시 확률':'다음 개미의 병원 출발 확률'}</p>`+decisions.map(d=>`<div style="margin-top:14px;color:#20313d"><b>${name(d.node)}</b>${d.picked?' · 선택 '+d.picked:''}</div>`+(d.choices.length?d.choices.map(c=>`<div class="prob"><span>${c.id}${c.id===d.picked?' ✓':''}</span><div class="bar"><i style="width:${c.p*100}%"></i></div><span>${(c.p*100).toFixed(1)}%</span></div>`).join(''):'<p>이동 가능한 도로 없음</p>')).join('');}
function chart(){const vals=history.filter(v=>v!==null),exact=M.dijkstra(edges)?.time;let upper=Math.max(15,...vals,exact||0)*1.1,lower=0;const x=i=>40+i/Math.max(history.length-1,1)*340,y=v=>130-(v-lower)/(upper-lower)*110;let s='';for(let i=0;i<4;i++){let v=upper*i/3;s+=`<line x1="40" y1="${y(v)}" x2="385" y2="${y(v)}" stroke="#e6ebed"/><text x="33" y="${y(v)+4}" text-anchor="end" font-size="10" fill="#819099">${v.toFixed(0)}</text>`;}if(Number.isFinite(exact))s+=`<line x1="40" y1="${y(exact)}" x2="385" y2="${y(exact)}" stroke="#a98655" stroke-dasharray="5 4"/>`;const pts=history.map((v,i)=>v===null?null:`${x(i)},${y(v)}`).filter(Boolean);if(pts.length)s+=`<polyline points="${pts.join(' ')}" fill="none" stroke="#087e83" stroke-width="2.5"/>`+history.map((v,i)=>v===null?'':`<circle cx="${x(i)}" cy="${y(v)}" r="2.5" fill="#087e83"/>`).join('');else s+='<text x="210" y="70" text-anchor="middle" font-size="12" fill="#819099">탐색을 시작하면 기록됩니다</text>';s+=`<text x="4" y="12" font-size="10" fill="#819099">분</text><text x="40" y="151" font-size="10" fill="#819099">1회</text><text x="365" y="151" font-size="10" fill="#819099">${history.length||0}회</text>`;$('chart').innerHTML=s;}
function render(){setStatus();drawMap();const exact=M.dijkstra(edges),shortest=M.dijkstra(edges,'distance');$('routeCards').innerHTML=Object.keys(M.routes).map(r=>{const p=M.evaluate(edges.filter(e=>e.route===r).map(e=>e.id),edges);return `<div class="routecard ${exact?.ids[0][0]===r?'best':''}"><b>경로 ${r}</b><span> ${exact?.ids[0][0]===r?'· 최소시간':''}</span><strong>${Number.isFinite(p.time)?f(p.time)+' <span>분</span>':'통행 불가'}</strong><span>${f(p.distance)} km${shortest?.ids[0][0]===r?' · 최단거리':''}</span></div>`;}).join('');$('recommend').innerHTML=best?`<div class="value">${routeName(best)} · ${f(best.time)}분</div><div class="routepath">${path(best)}</div><span class="sub">총 ${f(best.distance)} km · 출발 후 약 ${f(best.time)}분 도착</span>`:'<div class="value" style="font-size:19px">탐색을 시작하세요</div><p class="sub">재생 또는 한 단계 진행으로 개미를 출발시킵니다.</p>';
 $('exact').innerHTML=exact?`<b>다익스트라: ${routeName(exact)} · ${f(exact.time)}분</b><br>${path(exact)}<br>${best?(best.ids.join()===exact.ids.join()?'ACO와 경로 일치 · 시간 차이 0.0분':`ACO와 경로 다름 · 시간 차이 ${f(best.time-exact.time)}분`):'ACO 결과 대기 중'}`:'현재 통제 조건에서는 목적지에 도달할 수 없습니다.';
 if(previous){const old=previous.ids.length?M.evaluate(previous.ids,edges):null;$('comparison').innerHTML=`<b>변경 전</b> ${routeName(previous)} · ${f(previous.time)}${Number.isFinite(previous.time)?'분':''} <span class="sub">(${previous.source})</span><br><b>기존 경로를 그대로 이용하면</b> ${old?f(old.time)+(Number.isFinite(old.time)?'분':''):'경로 없음'}<br><b>변경 후 ACO</b> ${best?`${routeName(best)} · ${f(best.time)}분`:'재탐색 대기'}<br><b>변경 후 정확한 기준</b> ${exact?`${routeName(exact)} · ${f(exact.time)}분`:'도달 불가'}`;}
 $('records').innerHTML=records.slice().reverse().map((a,i)=>`<tr><td><button data-record="${records.length-1-i}" style="padding:3px 7px">${a.round}회 / ${a.number}번</button></td><td>${path(a)}</td><td>${f(a.distance)} km</td><td>${a.failed?'도달 실패':f(a.time)+'분'}</td></tr>`).join('');$('recordCount').textContent=`전체 ${iteration*config().count}마리 · 최근 ${records.length}개 표시`;
 $('roads').innerHTML=edges.map(e=>`<tr><td>${e.id} · ${name(e.from)} ↔ ${name(e.to)}</td><td>${f(e.length)} km</td><td>${f(e.speed/e.congestion)} km/h</td><td>${f(e.wait,0)}초</td><td>${e.closed?'통제':f(M.time(e))+'분'}</td><td>${f(e.tau,3)}</td></tr>`).join('');showProb();chart();}
function fillEditor(){const e=edges.find(e=>e.id===selected);$('edgeSelect').value=selected;['length','speed','wait','congestion'].forEach(k=>$(k).value=e[k]);$('closed').checked=e.closed;$('edgeTime').textContent=e.closed?'통제 중 · 경로 탐색에서 제외':`유효속도 ${f(e.speed/e.congestion)} km/h · 도로 시간 ${f(M.time(e),2)}분`;}
function selectEdge(id){selected=id;fillEditor();drawMap(progress);}
function frame(now){const delta=Math.min(now-lastFrame,100);lastFrame=now;if(running){if(!pending)begin();if(pending){progress+=delta/2200*Number($('playSpeed').value);if(progress>=1)commit();else{drawMap(progress);showProb(pending[0]);}}else running=false;setStatus();}requestAnimationFrame(frame);}
 $('edgeSelect').innerHTML=edges.map(e=>`<option value="${e.id}">${e.id} · ${name(e.from)} ↔ ${name(e.to)}</option>`).join('');$('edgeSelect').onchange=e=>selectEdge(e.target.value);
 $('map').addEventListener('click',e=>{const g=e.target.closest('[data-edge]');if(g)selectEdge(g.dataset.edge);});$('map').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){const g=e.target.closest('[data-edge]');if(g){e.preventDefault();selectEdge(g.dataset.edge);}}});
 ['length','speed','wait','congestion'].forEach(k=>$(k).addEventListener('input',()=>{if($(k).value===''||!$(k).validity.valid)return;roadChange(()=>edges.find(e=>e.id===selected)[k]=Number($(k).value));}));
 ['length','speed','wait','congestion'].forEach(k=>$(k).addEventListener('change',()=>{const v=normalize($(k));if(edges.find(e=>e.id===selected)[k]!==v)roadChange(()=>edges.find(e=>e.id===selected)[k]=v);}));
 $('closed').onchange=()=>roadChange(()=>edges.find(e=>e.id===selected).closed=$('closed').checked);
 ['count','limit','alpha','beta','rho'].forEach(k=>$(k).onchange=()=>{normalize($(k));clearSearch();});
 $('play').onclick=()=>{if(iteration>=config().limit)clearSearch();running=!running;setStatus();};$('step').onclick=()=>{running=false;if(iteration>=config().limit)clearSearch();if(!pending)begin();const example=pending?.[0];commit();if(example)showProb(example);};
 $('incident').onclick=()=>roadChange(()=>{edges=M.defaults();edges.find(e=>e.id==='B2').congestion=1+8/(1.1/30*60);selected='B2';});
 $('reset').onclick=()=>{edges=M.defaults();previous=null;selected='B2';for(const [k,v] of Object.entries({count:20,limit:40,alpha:1,beta:2,rho:.3,playSpeed:1}))$(k).value=v;$('comparison').textContent='도로를 편집하거나 ‘B 경로 사고·혼잡 예시’를 눌러 비교하세요.';clearSearch();fillEditor();};
 $('records').onclick=e=>{const btn=e.target.closest('[data-record]');if(btn)showProb(records[Number(btn.dataset.record)]);};
 render();fillEditor();requestAnimationFrame(frame);
