/* Browser-local ACO model. Time: minutes; length: km; speed: km/h. */
(function(root){
'use strict';
const nodes=[{id:'H',x:85,y:255,name:'병원'},{id:'A1',x:245,y:100,name:'북문'},{id:'A2',x:505,y:100,name:'시청'},{id:'B1',x:270,y:255,name:'중앙역'},{id:'B2',x:490,y:255,name:'시장'},{id:'C1',x:230,y:430,name:'공원'},{id:'C2',x:530,y:430,name:'강변'},{id:'D',x:710,y:255,name:'사고 현장'}];
const routes={A:['H','A1','A2','D'],B:['H','B1','B2','D'],C:['H','C1','C2','D']};
function defaults(){return Object.entries(routes).flatMap(([r,ns])=>ns.slice(0,-1).map((n,i)=>({id:r+(i+1),from:n,to:ns[i+1],route:r,length:({A:[.8,.8,.8],B:[1,1.1,1],C:[1.1,1.3,1.1]})[r][i],speed:30,wait:({A:[144,144,144],B:[56,56,56],C:[80,80,80]})[r][i],congestion:1,closed:false,tau:1})));}
const time=e=>e.length/(e.speed/e.congestion)*60+e.wait/60;
function evaluate(ids,edges){const es=ids.map(id=>edges.find(e=>e.id===id));return {ids:[...ids],time:es.some(e=>!e||e.closed)?Infinity:es.reduce((s,e)=>s+time(e),0),distance:es.reduce((s,e)=>s+(e?e.length:0),0)};}
function choices(node,visited,edges,alpha,beta){const es=edges.filter(e=>!e.closed&&(e.from===node||e.to===node)&&!visited.includes(e.from===node?e.to:e.from));const logs=es.map(e=>alpha*Math.log(Math.max(e.tau,1e-12))-beta*Math.log(time(e)));const max=Math.max(...logs);const weights=logs.map(v=>Math.exp(v-max));const sum=weights.reduce((a,b)=>a+b,0);return es.map((e,i)=>({id:e.id,next:e.from===node?e.to:e.from,p:weights[i]/sum,time:time(e)}));}
function ant(edges,alpha,beta,rng=Math.random){let visited=['H'],ids=[],decisions=[];while(visited.at(-1)!=='D'){const node=visited.at(-1),cs=choices(node,visited,edges,alpha,beta);if(!cs.length)return {ids,nodes:visited,time:Infinity,distance:evaluate(ids,edges).distance,decisions,failed:true};let r=rng(),pick=cs.at(-1);for(const c of cs){r-=c.p;if(r<=0){pick=c;break;}}decisions.push({node,choices:cs,picked:pick.id});ids.push(pick.id);visited.push(pick.next);}return {...evaluate(ids,edges),nodes:visited,decisions,failed:false};}
function iteration(edges,{count,alpha,beta,rho},rng=Math.random){const ants=Array.from({length:count},()=>ant(edges,alpha,beta,rng));edges.forEach(e=>e.tau=Math.max(1e-12,e.tau*(1-rho)));for(const a of ants)if(!a.failed)for(const id of a.ids)edges.find(e=>e.id===id).tau+=10/a.time;return ants;}
function dijkstra(edges,metric='time'){const dist={H:0},prev={},done=new Set();while(true){const u=nodes.filter(n=>!done.has(n.id)&&Number.isFinite(dist[n.id])).sort((a,b)=>dist[a.id]-dist[b.id])[0]?.id;if(!u)break;if(u==='D')break;done.add(u);for(const e of edges.filter(e=>!e.closed&&(e.from===u||e.to===u))){const v=e.from===u?e.to:e.from,alt=dist[u]+(metric==='time'?time(e):e.length);if(alt<(dist[v]??Infinity)){dist[v]=alt;prev[v]={u,id:e.id};}}}if(!Number.isFinite(dist.D))return null;let ns=['D'],ids=[],u='D';while(u!=='H'){ids.unshift(prev[u].id);u=prev[u].u;ns.unshift(u);}return {...evaluate(ids,edges),nodes:ns};}
root.ACO={nodes,routes,defaults,time,evaluate,choices,ant,iteration,dijkstra};
})(typeof window==='undefined'?globalThis:window);
